spring:
  application:
    name: Client
  datasource:
    url: jdbc:postgresql://localhost:5432/pizza_db
    username: user
    password: user

mqtt:
  broker-url: tcp://mosquitto:1883
  client-id: AwesomePizza
  username: user
  password: user
  publish-qos: 1
  order-topic: order